// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $BuscarHechizo from "./routes/BuscarHechizo.tsx";
import * as $BuscarPersonaje from "./routes/BuscarPersonaje.tsx";
import * as $ListEstudiantes from "./routes/ListEstudiantes.tsx";
import * as $ListPersonajes from "./routes/ListPersonajes.tsx";
import * as $ListPersonal from "./routes/ListPersonal.tsx";
import * as $ListaHechizos from "./routes/ListaHechizos.tsx";
import * as $ListaPorCasas from "./routes/ListaPorCasas.tsx";
import * as $Personaje_id_ from "./routes/Personaje/[id].tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $houses_house_ from "./routes/houses/[house].tsx";
import * as $index from "./routes/index.tsx";
import * as $BuscarPorPersonaje from "./islands/BuscarPorPersonaje.tsx";
import * as $BuscarPorhechizo from "./islands/BuscarPorhechizo.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/BuscarHechizo.tsx": $BuscarHechizo,
    "./routes/BuscarPersonaje.tsx": $BuscarPersonaje,
    "./routes/ListEstudiantes.tsx": $ListEstudiantes,
    "./routes/ListPersonajes.tsx": $ListPersonajes,
    "./routes/ListPersonal.tsx": $ListPersonal,
    "./routes/ListaHechizos.tsx": $ListaHechizos,
    "./routes/ListaPorCasas.tsx": $ListaPorCasas,
    "./routes/Personaje/[id].tsx": $Personaje_id_,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/houses/[house].tsx": $houses_house_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/BuscarPorPersonaje.tsx": $BuscarPorPersonaje,
    "./islands/BuscarPorhechizo.tsx": $BuscarPorhechizo,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
